"""adding indexes on instances and attendance

Revision ID: 01807f1d41da
Revises: 760bee3701a9
Create Date: 2025-05-18 07:49:28.499158

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01807f1d41da"
down_revision: Union[str, None] = "760bee3701a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_attendance_event_instance_id", "attendance", ["event_instance_id"], unique=False)
    op.create_index("idx_attendance_is_planned", "attendance", ["is_planned"], unique=False)
    op.create_index("idx_attendance_user_id", "attendance", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_attendance_user_id", table_name="attendance")
    op.drop_index("idx_attendance_is_planned", table_name="attendance")
    op.drop_index("idx_attendance_event_instance_id", table_name="attendance")
    # ### end Alembic commands ###
