"""Making org_type_id and org_id nullable on Position

Revision ID: 38484f89e64b
Revises: b0e9df27eac0
Create Date: 2024-11-29 09:47:40.312576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38484f89e64b'
down_revision: Union[str, None] = 'b0e9df27eac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'org_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('positions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('positions', 'org_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
