"""adding ao_id to update_requests

Revision ID: 5b56bd54a1a1
Revises: a43323c64d67
Create Date: 2025-04-11 09:22:56.952267

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b56bd54a1a1"
down_revision: Union[str, None] = "a43323c64d67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("update_requests", sa.Column("ao_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "update_requests", "orgs", ["ao_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "update_requests", type_="foreignkey")
    op.drop_column("update_requests", "ao_id")
    # ### end Alembic commands ###
