"""create magic link tables

Revision ID: 5c3d6d2cc8eb
Revises: 38484f89e64b
Create Date: 2024-12-02 06:46:25.124799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5c3d6d2cc8eb"
down_revision: Union[str, None] = "38484f89e64b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magiclinkauthrecord",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("otp_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "expiration",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("client_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recent_attempts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "magiclinkauthsession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("persistent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "expiration",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("magiclinkauthsession", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_magiclinkauthsession_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_magiclinkauthsession_persistent_id"),
            ["persistent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_magiclinkauthsession_session_token"),
            ["session_token"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("magiclinkauthsession", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_magiclinkauthsession_session_token"))
        batch_op.drop_index(batch_op.f("ix_magiclinkauthsession_persistent_id"))
        batch_op.drop_index(batch_op.f("ix_magiclinkauthsession_email"))

    op.drop_table("magiclinkauthsession")
    op.drop_table("magiclinkauthrecord")
    # ### end Alembic commands ###
