"""adding is_active flag to event_tags

Revision ID: 68b233d305c2
Revises: 613421f1ea52
Create Date: 2025-09-11 10:16:48.129376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68b233d305c2"
down_revision: Union[str, None] = "613421f1ea52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_tags", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.sql.expression.true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_tags", "is_active")
    # ### end Alembic commands ###
