"""taking is_active off event_tags and positions temp

Revision ID: 6bb50b8557fe
Revises: ebe24ae4b039
Create Date: 2025-10-13 06:45:37.815074

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bb50b8557fe"
down_revision: Union[str, None] = "ebe24ae4b039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column("event_tags", "is_active")
    op.drop_column("positions", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions",
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.add_column(
        "event_tags",
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
