"""changing achievement threshold type to str

Revision ID: 6cfc0d3d89b8
Revises: 6bb50b8557fe
Create Date: 2025-11-24 08:59:57.360592

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cfc0d3d89b8"
down_revision: Union[str, None] = "6bb50b8557fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "achievements",
        "auto_threshold_type",
        existing_type=postgresql.ENUM("posts", "unique_aos", name="achievement_threshold_type"),
        type_=sa.String(),
        existing_nullable=True,
    )
    sa.Enum("posts", "unique_aos", name="achievement_threshold_type").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("posts", "unique_aos", name="achievement_threshold_type").create(op.get_bind())
    op.alter_column(
        "achievements",
        "auto_threshold_type",
        existing_type=sa.String(),
        type_=postgresql.ENUM("posts", "unique_aos", name="achievement_threshold_type"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
