"""Changing user email index to ignore case

Revision ID: 81a812f162bf
Revises: b1831f06a503
Create Date: 2025-03-19 05:38:18.535088

"""

from typing import Sequence, Union

import sqlalchemy as sa
from citext import CIText

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81a812f162bf"
down_revision: Union[str, None] = "b1831f06a503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index("idx_users_email", "users", [sa.text("lower('email')")], unique=True)
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(), nullable=False, type_=CIText(), postgresql_using="email::citext"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_email", table_name="users")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.alter_column("users", "email", existing_type=CIText(), nullable=False, type_=sa.VARCHAR())
    # ### end Alembic commands ###
