"""Adding period dimension to achievements_x_users

Revision ID: 88f549c87890
Revises: ff14e58e09f3
Create Date: 2025-07-10 11:05:21.917105

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88f549c87890"
down_revision: Union[str, None] = "ff14e58e09f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # clear achievements_x_users table to avoid conflicts with new columns
    op.execute("TRUNCATE TABLE achievements_x_users")
    op.add_column("achievements_x_users", sa.Column("award_year", sa.Integer(), server_default="-1", nullable=False))
    op.add_column("achievements_x_users", sa.Column("award_period", sa.Integer(), server_default="-1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("achievements_x_users", "award_period")
    op.drop_column("achievements_x_users", "award_year")
    # ### end Alembic commands ###
