"""adding is_private flags to events and event_instances

Revision ID: 890a5f8c1ce1
Revises: d0309a0e2477
Create Date: 2025-11-25 06:54:40.714230

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "890a5f8c1ce1"
down_revision: Union[str, None] = "d0309a0e2477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("is_private", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false())
    )
    op.add_column(
        "event_instances",
        sa.Column("is_private", sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "is_private")
    op.drop_column("event_instances", "is_private")
    # ### end Alembic commands ###
