"""adding soft delete flags to positions and tags

Revision ID: d0309a0e2477
Revises: 6cfc0d3d89b8
Create Date: 2025-11-25 06:50:32.170964

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0309a0e2477"
down_revision: Union[str, None] = "6cfc0d3d89b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_tags", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.sql.expression.true())
    )
    op.add_column(
        "positions", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.sql.expression.true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_tags", "is_active")
    op.drop_column("positions", "is_active")
    # ### end Alembic commands ###
