"""convert times to str

Revision ID: e41f29d2b687
Revises: 4e0673582e75
Create Date: 2025-02-14 11:14:01.189537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e41f29d2b687"
down_revision: Union[str, None] = "4e0673582e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "start_time",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="TO_CHAR(start_time, 'HH24MI')",
    )
    op.alter_column(
        "events",
        "end_time",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="TO_CHAR(end_time, 'HH24MI')",
    )
    op.alter_column(
        "update_requests",
        "event_start_time",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="TO_CHAR(event_start_time, 'HH24MI')",
    )
    op.alter_column(
        "update_requests",
        "event_end_time",
        existing_type=postgresql.TIME(),
        type_=sa.String(),
        existing_nullable=True,
        postgresql_using="TO_CHAR(event_end_time, 'HH24MI')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "update_requests",
        "event_end_time",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
        postgresql_using="TO_TIMESTAMP(event_end_time, 'HH24MI')",
    )
    op.alter_column(
        "update_requests",
        "event_start_time",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
        postgresql_using="TO_TIMESTAMP(event_start_time, 'HH24MI')",
    )
    op.alter_column(
        "events",
        "end_time",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
        postgresql_using="TO_TIMESTAMP(end_time, 'HH24MI')",
    )
    op.alter_column(
        "events",
        "start_time",
        existing_type=sa.String(),
        type_=postgresql.TIME(),
        existing_nullable=True,
        postgresql_using="TO_TIMESTAMP(start_time, 'HH24MI')",
    )
    # ### end Alembic commands ###
