"""adding is_active flag to positions

Revision ID: ebe24ae4b039
Revises: 68b233d305c2
Create Date: 2025-09-28 07:01:56.688244

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebe24ae4b039"
down_revision: Union[str, None] = "68b233d305c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "is_active")
    # ### end Alembic commands ###
