"""adding series_exception

Revision ID: f676d53e006c
Revises: 890a5f8c1ce1
Create Date: 2026-03-01 05:43:42.919737

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f676d53e006c"
down_revision: Union[str, None] = "890a5f8c1ce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("closed", "different-time", "miscellaneous", name="series_exception").create(op.get_bind())
    op.add_column(
        "event_instances",
        sa.Column(
            "series_exception",
            postgresql.ENUM("closed", "different-time", "miscellaneous", name="series_exception", create_type=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_instances", "series_exception")
    sa.Enum("closed", "different-time", "miscellaneous", name="series_exception").drop(op.get_bind())
    # ### end Alembic commands ###
