"""Renaming + adding emergency info to Users

Revision ID: fdce925467c7
Revises: bc8d946e6cf2
Create Date: 2024-12-19 13:36:24.759599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdce925467c7"
down_revision: Union[str, None] = "bc8d946e6cf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orgs_x_slack_spaces",
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("slack_space_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_space_id"],
            ["slack_spaces.id"],
        ),
        sa.PrimaryKeyConstraint("org_id", "slack_space_id"),
    )
    op.drop_table("org_x_slack")
    op.add_column("users", sa.Column("emergency_contact", sa.String(), nullable=True))
    op.add_column("users", sa.Column("emergency_phone", sa.String(), nullable=True))
    op.add_column("users", sa.Column("emergency_notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "emergency_notes")
    op.drop_column("users", "emergency_phone")
    op.drop_column("users", "emergency_contact")
    op.create_table(
        "org_x_slack",
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("slack_space_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["orgs.id"], name="org_x_slack_org_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["slack_space_id"],
            ["slack_spaces.id"],
            name="org_x_slack_slack_space_id_fkey",
        ),
        sa.PrimaryKeyConstraint("org_id", "slack_space_id", name="org_x_slack_pkey"),
    )
    op.drop_table("orgs_x_slack_spaces")
    # ### end Alembic commands ###
