name: Run Alembic Migrations

on:
  push:
    branches:
      - main

jobs:
    alembic_migration:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v3
          with:
            python-version: '3.12'
        - uses: 'google-github-actions/auth@v2'
          with:
            service_account: ${{ secrets.GCP_AUTH_SERVICE_ACCOUNT }}
            workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install --no-root
        - name: Set up environment variables
          run: |
              echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> $GITHUB_ENV
              echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
              echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
              echo "DATABASE_SCHEMA=f3_dev" >> $GITHUB_ENV
              echo "USE_GCP=True" >> $GITHUB_ENV

        - name: Run Alembic migrations
          run: |
              poetry run alembic upgrade head